### ISSUE TITLE
rename `before` and `after` in the definitions

### ISSUE THREAD

**Issue by iGEL** [holidays/definitions#117]
The labels `before` and `after` for `year_ranges` are confusing, as the words usually don't include the point in time they refer to (e.g.: "after 2018" usually means, from 2019 on). I think, `before` should be named `until` and `after` should be named `from`

So, instead of
```yaml
7:
  name: 振替休日
  regions: [jp]
  mday: 1
  year_ranges:
    - before: 2002
```
I suggest to write:
```yaml
7:
  name: 振替休日
  regions: [jp]
  mday: 1
  year_ranges:
    - until: 2002
```

The only question to me would be how to handle the upgrade path before releasing a 5.0.0. Maybe it would be best to just add the new words to the definition and remove the old ones only with the new major release?
