### ISSUE TITLE
Add Juneteenth holiday to NYSE calendar

### ISSUE THREAD

**Issue by vassilios** [holidays/definitions#222]
Effective from 2022, NYSE (and other exchanges like NASDAQ and CBOE) will be closed on Juneteenth.

Under this change to [NYSE Rule 7.2](https://nyseguide.srorules.com/rules/document?treeNodeId=csh-da-filter!WKUS-TAL-DOCS-PHC-%7B4A07B716-0F73-46CC-BAC2-43EB20902159%7D--WKUS_TAL_19401%23teid-15), the Exchange will be closed on June 19th of each year going forward. If the holiday falls on a Saturday, the Exchange will be closed the preceding Friday – and if it falls on a Sunday, the Exchange will be closed the succeeding Monday. This rule change brings the number of NYSE market holidays to ten.

See relevant announcement:
https://www.thecorporatecounsel.net/blog/2021/10/nyse-makes-juneteenth-a-new-market-holiday.html

NYSE holidays schedule: https://www.nyse.com/markets/hours-calendars

There are other pull requests which implement Juneteenth for other calendars (see for example:
https://github.com/holidays/definitions/pull/195 )

For the NYSE calendar, we would require this to start from year 2022 using something like the following:

```yaml
  6:
  - name: Juneteenth National Independence Day
    regions: [nyse]
    mday: 19
    observed: to_weekday_if_weekend(date)
    year_ranges:
      from: 2022
```
