### ISSUE TITLE
Change 'methods' in definitions to be more generic

### ISSUE THREAD

**Issue by ppeble** [holidays/definitions#24]
This one is gonna be tough. In order to complete the transition to completely generic YAML in our definitions (thereby allowing the definitions to be used in other languages) we will need to come up with a DSL for removing the current ruby code that makes up the definitions. I don't have solid ideas yet for what we will do but I will use this issue as a way to propose ideas going forward.

Example:

```yaml
afl_grand_final:
    arguments: year
    source: |
      case year
      when 2015
        Date.civil(2015, 10, 2)
      when 2016
        Date.civil(2016, 9, 30)
      when 2017
        Date.civil(2017, 9, 29)
      end
```

This could be done as follows:

```yaml
afl_grand_final:
    arguments: year
    logic:
      if:
        argument: year
        value: 2015
        then: 2015-10-2
      if:
        argument: year
        value: 2016
        then: 2016-9-30
      if:
        argument: year
        value: 2017
        then: 2017-9-29
```

There are a few immediate concerns:

1) There is some relatively complex logic in some of the methods. It might be difficult to make a DSL that isn't just...ruby-like. I'm not sure how to approach this.
2) There are a few cases where a method will call one of our 'common' methods. For example, 'easter' is a 'common' method that anyone can call but are considered 'private' inside of the ruby holidays code. I think we would need to define these 'common' methods in these definitions and then make them callable somehow. This could be very difficult.
