### ISSUE TITLE
Missing Holidays for Romania: January 6th and 7th

### ISSUE THREAD

**Issue by hariprasath-vengateasan** [holidays/definitions#296]
The holidays “Boboteaza” (January 6th) and “Sfântul Ioan Botezătorul” (January 7th) have been officially observed in Romania starting from 2024, but they are missing from the ro.yaml file.

Proposed Update:

Add the following to the months section for January in ro.yaml:
```
  1:
    - name: "Boboteaza"
      regions: [ro]
      mday: 6
      year_ranges:
         from: 2024
    - name: "Sfântul Ioan Botezătorul"
      regions: [ro]
      mday: 7
      year_ranges:
         from: 2024
```

Reference:
	• Wikipedia: [Public holidays in Romania](http://en.wikipedia.org/wiki/Public_holidays_in_Romania)

This update ensures the accuracy of Romanian holidays starting from 2024.

Thank you!
