### ISSUE TITLE
Change 'tests' in definitions to be more generic

### ISSUE THREAD

**Issue by ppeble** [holidays/definitions#7]
Right now all of the 'tests' are ruby. This has to change if we want to use these definitions in other languages. We need a format that can express all of the tests that exist today in a YAML format.

My proposal:

``` yaml
tests:
  - name: "New Year's Day"
    year: 2015
    month: 1
    day: 1
    regions: ['us']
  - name: Columbus Day
    year: 2015
    month: 10
    day: 10
    options: ['observed']
    regions: ['us']
  - name: "Phil's Birthday!"
    year: 2015
    month: 8
    day: 8
    options: ['informal']
    regions: ['us']
  - name: "Something"
    year_range: 2014..2020
    month: 1
    day: 1
    options: ['observed']
    regions: ['us', 'uk']
  - name: "Else"
    year: 2016
    month: 6
    day: 15
    valid: false
    regions: ['us']
```

The region should be implicit based on the current file being tested.

I'm going to try to do this now and the modify the ruby repository to generate based on these new definitions. If I do it right then the generated classes will look identical to the existing ones.

**Comment by ttwo32** [comment]
:+1:

**Comment by ptrimble** [comment]
Slight modification here. Instead of `found` I am going with `valid: false`. The `found` usage just....felt weird. I'm not sure `valid` makes much more sense but we'll stick with it for the moment.

**Comment by ptrimble** [comment]
Aaaaannnnnnddd I've hit my first real problem. The above setup won't work unless I also include the region. We can't assume based on the file because of subregions. We'll need to add in a 'region' key. :frowning_face:

**Comment by iGEL** [comment]
I was thinking about this. First of all, I would suggest to have a `date` instead of `day`, `month` & `year`. And I also don't really like the `valid` thing. Usually, tests are written in a "given these inputs, I expect these results". I think, that could be expressed more clearly here, maybe like this:

```yml
tests:
  - given:
      date: 2015-01-01
      regions: ["us"] # could be optional unless you want to have something different than the files main locale
    expect:
      name: "New Year's Day"
      holiday: true
  - given:
      date: 2015-10-10
      observed: true
    expect:
      name: Columbus Day
  - given:
      date: 2016-06-15
    expect:
      holiday: false
```

That would generate these tests:

* 2015-01-01 is a holiday
* 2015-01-01 is "New Year"s Day"
* observed 2015-10-10 is Columbus Day
* 2016-06-15 is not a holiday
