### ISSUE TITLE
Wrong definition for the German holiday "Reformationstag" for the year 2017

### ISSUE THREAD

**Issue by jensberke** [holidays/definitions#73]
Hi,

"Reformationstag" is a German regular holiday on October 31st each year for the regions de_bb, de_mv, de_sn, de_st, de_th **only**, and informal for de_bw.

The year 2017 is an exception from this rule: it's a holiday in **all** regions in Germany in this year, and in this year **only**.

The definition of this holiday is wrong for years != 2017. It should yield **no** results if a region is specified and the region is not one from the list mentioned above. Example for de_ni in 2018:

Wrong:

```
Holidays.on(Date.civil(2018,10,31), :de_ni)
 => [{:date=>Wed, 31 Oct 2018, :name=>"Reformationstag", 
      :regions=>[:de_sh, :de_ni, :de_hh, :de_hb, :de_be, :de_bb, :de_mv, :de_sn, :de_st, :de_th]}]
```

Expected:

```
Holidays.on(Date.civil(2018,10,31), :de_ni)
 => []
```
Holidays version: 6.1.0

**Comment by spaceneedle2019** [comment]
```
  - name: Reformationstag
    regions: [de_sh, de_ni, de_hh, de_hb, de_be, de_bb, de_mv, de_sn, de_st, de_th]
    mday: 31
  - name: Reformationstag
    regions: [de_bw]
    mday: 31
    type: informal
  - name: Reformationstag
    regions: [de]
    mday: 31
    year_ranges:
    - limited: [2017]
```

As you can see above, it is already defined that _Reformationstag_ is informal in `de_bw` and only a national bank holiday in the year 2017 because of the Reformation 500th Anniversary.  It was my fault  that `de_ni` currently shows this holiday before and after 2017. I've added some new regions to the definition file.

The right set should be `[de_bb, de_mv, de_sn, de_st, de_th]`

@ppeble, I have two questions for you:

1. Shall I correct the definition file?
2. Is there a way to (re-)include de_sh, de_ni, de_hh, de_hb, de_be without a special holiday definition for these regions?
